---
- hosts: all
  tasks:
    - name: Install curl, git, tmux
      become: true
      apt:
        pkg:
        - curl
        - git
        - tmux
        update_cache: yes
    - name: Install asdf-vm
      command: "{{item}}"
      with_items:
        - git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.8.0
      ignore_errors: yes
    - name: Add asdf command to shell
      lineinfile:
        path: /home/vagrant/.profile
        regexp: 'asdf.sh$'
        line: '. $HOME/.asdf/asdf.sh'
        insertbefore: BOF
    # 需要登录vagrant虚拟机之后手动运行
    # - name: Install ruby
      # command: "{{item}}"
      # with_items:
        # - source /home/vagrant/.profile
        # - asdf plugin add ruby
        # - asdf install ruby 2.7.1
        # - asdf global ruby 2.7.1
        # - gem install bundler
      # ignore_errors: yes
    - name: Remove old docker
      become: true
      apt:
        pkg:
        - docker
        - docker-engine
        - docker.io
        - containerd
        - runc
        state: absent
    - name: Install latest docker
      command: "{{item}}"
      become: true
      with_items:
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
        - apt-key fingerprint 0EBFCD88
        - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
        - apt update
        - apt install -y docker-ce docker-ce-cli containerd.io
      ignore_errors: yes
    - name: Install docker compose
      become: true
      shell: |
        curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
